### ISSUE TITLE
TypeError when trying to open app via localhost:3000

### ISSUE THREAD

**Issue by 28n** [haydenbleasel/next-forge#313]
**Describe the bug**
When i am trying to open http://localhost:3000, after following the setup guide in next-forge docs step by step, i am met with an "Internal Server Error" in my browser, and the following logs in console:

> web:dev: ✦Aj WARN Using 127.0.0.1 as IP address in development mode
web:dev:  ○ Compiling / ...
web:dev:  ✓ Compiled / in 6.5s
web:dev:  GET / 200 in 7938ms
web:dev: (node:29924) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
web:dev: (Use `node --trace-deprecation ...` to show where the warning was created)
app:dev:  ○ Compiling / ...
app:dev:  ✓ Compiled / in 8.2s
app:dev: TypeError: The "payload" argument must be of type object. Received null
app:dev:     at frame (..\..\node_modules\.pnpm\next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1\node_modules\next\src\server\patch-error-inspect.ts:89:42)
app:dev:     at getSourcemappedFrameIfPossible (..\..\node_modules\.pnpm\next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1\node_modules\next\src\server\patch-error-inspect.ts:179:32)
app:dev:     at parseAndSourceMap (..\..\node_modules\.pnpm\next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1\node_modules\next\src\server\patch-error-inspect.ts:234:23)
app:dev:     at exit (..\..\node_modules\.pnpm\next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1\node_modules\next\src\server\patch-error-inspect.ts:224:32)
app:dev:     at apply (webpack://next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-server.edge.development.js:569:32)
app:dev:     at apply (webpack://next/dist/compiled/react-server-dom-turbopack/cjs/react-server-dom-turbopack-server.node.development.js:593:32)
app:dev:     at error (..\..\node_modules\.pnpm\next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1\node_modules\next\src\server\lib\router-server.ts:586:18)
app:dev:     at async Server.requestListener (..\..\node_modules\.pnpm\next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1\node_modules\next\src\server\lib\start-server.ts:146:6) {
app:dev:   code: 'ERR_INVALID_ARG_TYPE'
app:dev: }
app:dev:  GET / 500 in 9462ms

Additionally, i have encountered that navigating to /sign-up works in the browser (page renders), but the console still outputs the same error.

Upgraded node and pnpm, also tried pnpm update in monorepo root, none fixes the error.

**next-forge version**
I am using version 2.18.24

**To Reproduce**
1. Install next-forge template as per https://docs.next-forge.com/setup
2. Run pnpm dev
3. Open localhost:3000

**Expected behavior**
Seeing the app without this error, only apps/app seems to be encountering this error, apps/web, apps/api, apps/studio etc. works

**Screenshots**
![browserError](https://github.com/user-attachments/assets/fef1ea78-a5c5-43fc-807d-95dfce7dc921)
![consoleError](https://github.com/user-attachments/assets/92666765-434a-4f7a-ad95-7738167971b5)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 (sadly)
 - Browser Chrome v131, same Behaviour in Opera, Firefox and Microsoft Edge

**Comment by 28n** [comment]
Just tried the same setup on a MacOS-based machine, and on there it works. Also spun up a windows VM, works fine on there too. Seems to be an issue on my end, so closing this issue! :)
