### ISSUE TITLE
Build fails after fresh init of new project due to "File is not defined" when prerendering "/_not-found" in "apps/app"

### ISSUE THREAD

**Issue by shiftynick** [haydenbleasel/next-forge#377]
**Describe the bug**
When trying to use `pnpm build`, the apps\app build fails with: 
│ Error occurred prerendering page "/_not-found". 
│ ReferenceError: File is not defined
 
Next.Js is creating the _not-found page, so it must be some other dependency???

**next-forge version**
2.21.11

**To Reproduce**
1. `npx next-forge@latest init my-app`
2. `cd my-app`
3. Fill in all `.env.local` and `.env` files with ALL variables
4. `pnpm install`
5. `pnpm build'
6. See error

**Expected behavior**
A successful build of all apps/packages

**Output**
┌ app#build > cache miss, executing 3b31f3c87ce2d737
│
│ > app@ build C:\Code\system2-monorepo\apps\app
│ > next build
│
│    ▲ Next.js 15.1.0
│    - Environments: .env.local
│
│    Creating an optimized production build ...
│  ✓ Compiled successfully
│  ✓ Linting and checking validity of types
│  ✓ Collecting page data
│ Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
│ ReferenceError: File is not defined
│     at C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:154720
│     at T (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:135126)
│     at ta (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:154638)
│     at nR (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:210724)
│     at oQ._send_request (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:292447)
│     at nm.call (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:205605)
│     at oQ._loaded (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:291645)
│     at oQ._init (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:290123)
│     at oQ.init (C:\Code\system2-monorepo\apps\app\.next\server\chunks\325.js:40:285388)
│     at 28941 (C:\Code\system2-monorepo\apps\app\.next\server\chunks\438.js:1:6554)
│ Export encountered an error on /_not-found/page: /_not-found, exiting the build.
│  ⨯ Static worker exited with code: 1 and signal: null
│  ELIFECYCLE  Command failed with exit code 1.
│
│ command finished with error: command (C:\Code\system2-monorepo\apps\app) C:\Program Files\nodejs\pnpm.cmd run build exited (1)
└────>

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser n/a

**Comment by shiftynick** [comment]
Ok, so it is something to do with the PostHog setup.

Removing the use of the <PostHogIdentifier/> (and also the <PostHogProvider/> on the web project) clears up the issues.

I'm new to React and SSR after many years in Vue, but it looks like some client-y stuff (File) is being called on server sider rendering??

**Comment by haydenbleasel** [comment]
Hey @shiftynick, thanks for reporting this! This was an issue in v2 where PostHog's client SDK (posthog-js) was getting pulled into the server-side render tree during prerendering, which caused the `File is not defined` error since that's a browser-only API.

In the current version (v6), the analytics setup has been completely refactored — PostHog initialization is now isolated to client instrumentation (`instrumentation-client.ts`) and the server-side code uses `posthog-node` instead. The provider component no longer imports `posthog-js` at all, so this shouldn't be an issue anymore.

Going to close this one out as it's been resolved by the architectural changes in newer versions. If you're still hitting this on a recent version, feel free to reopen!
